### PR TITLE
Update languages

### PR DESCRIPTION
**Pull request by cumbumking**

### CODE REVIEW

**Review by ranicumbum — COMMENTED** [review]
i need to add one more line also

**Comment by cumbumking** [comment]
i will add within 5 min

**Comment by ranicumbum** [comment]
i need to do urgent.pls make it fast

**Comment by cumbumking** [comment]
ok

**Comment by ranicumbum** [comment]
completed na

**Comment by ranicumbum** [comment]
kk

**Comment by ranicumbum** [comment]
that correction was good..we shall to complete the request

**Comment by cumbumking** [comment]
ok boss

**Comment by cumbumking** [comment]
thank you

**Comment by ranicumbum** [comment]
kk

**Comment by ranicumbum** [comment]
hi man

**Pull request merged**
